# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5930eb4d279f058827636acecc6d276c6eac9c0061427d76559fe43a20fb21e4660ab283dc670f5f6607a99153929290540f8bc09456ce1c1fabc90aa7f07ebb

test:
  secret_key_base: 953571bd48602c747ed72ae67137feb7484702094d82884c1e344c75e7732787c25fce36654d91a190a30d2a8757282fac0c85c0860490807308ed1278a94ede

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
